version: '3'
services:
  base:
    image: jprime/mmonad:base
    build:
      context: .
      dockerfile: docker/base/Dockerfile
  development:
    image: jprime/mmonad:development
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    depends_on:
      - base
  req_rep:
    image: jprime/mmonad:example-req-rep
    build:
      context: docker/examples
      dockerfile: request_reply/Dockerfile
    depends_on:
      - base